sudo: required
services:
  - docker

before_install:
  - docker build -t datnguyentan/frontend-docker -f Dockerfile.dev .

script:
  - docker run datnguyentan/frontend-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-333674319299'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY