language: node_js
node_js:
  - 14
services:
  - docker

before_install:
  - docker build -t datnguyentan/frontend-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true datnguyentan/frontend-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'react-docker'
  env: 'ReactDocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-333674319299'
  bucket_path: 'frontend-docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  cleanup: true
